### YamlMime:Role 
title: Data Engineer 
metadata: 
  title: Data Engineer 
  description: Data Engineers design and implement the management, monitoring, security, and privacy of data using the full stack of data services.
uid: role.data-engineer 
summary: | 
  Data Engineers design and implement the management, monitoring, security, and privacy of data using the full stack of data services.
subTitle: Data Engineers design and implement the management, monitoring, security, and privacy of data using the full stack of data services.
certificationPaths: 
- title: Azure Data Engineer
  linkedInKeywords: Azure Data Engineer
  uid: certification-path.azure-data-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-data-engineer
    levels:
    - intermediate  
certifications:
- uid: certification.azure-data-engineer
  requiredExams:
  - uid: exam.dp-203
resources:
- title: Microsoft Training and Certifications Guide
  description: Explore all certifications in a concise training and certifications guide.
  href: https://aka.ms/TrainingCertDeck
- title: Training and Certifications Poster
  description: Choose your path to success with this training and certifications poster.
  href: https://aka.ms/traincertposter
- title: Support for certifications
  href: ../help.md
  description: Get help through Microsoft Certification support forums. A forum moderator will respond in one business day, Monday-Friday.
