### YamlMime:Role 
title: Developer 
metadata: 
  title: Developer 
  description: Developers design, build, test, and maintain solutions. Developers implement applications and services by partnering with Solution Architects and customers.
uid: role.developer 
summary: | 
  Developers design, build, test, and maintain solutions. Developers implement applications and services by partnering with Solution Architects and customers. 
subTitle: Developers design, build, test and maintain cloud solutions.
certificationPaths: 
- title: Azure Developer
  linkedInKeywords: Azure Developer
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Dynamics 365 Finance and Operations Apps Developer
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Developer
  uid: certification-path.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Microsoft 365 Developer
  linkedInKeywords: Microsoft 365 Developer
  uid: certification-path.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
- title: Power Platform Developer
  linkedInKeywords: Power Platform Developer
  uid: certification-path.power-platform-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-204
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-platform-developer-associate
  requiredExams:
  - uid: exam.pl-400
- uid: certification.azure-iot-developer-specialty
  requiredExams:
  - uid: exam.az-220
resources:
- title: Microsoft Training and Certifications Guide
  description: Explore all certifications in a concise training and certifications guide.
  href: https://aka.ms/TrainingCertDeck
- title: Training and Certifications Poster
  description: Choose your path to success with this training and certifications poster.
  href: https://aka.ms/traincertposter
- title: Support for certifications
  href: ../help.md
  description: Get help through Microsoft Certification support forums. A forum moderator will respond in one business day, Monday-Friday.
